before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ '{{ incpatch .Version }}' }}-next"

brews:
  - tap:
      owner: "{{cookiecutter.github_username}}"
      name: "{{cookiecutter.project_slug}}"

    commit_msg_template: "Brew formula update for {{ '{{ .ProjectName }}' }} version {{ '{{ .Tag }}' }} [skip ci]"

    folder: HomebrewFormula

    homepage: "https://github.com/{{cookiecutter.github_username}}/{{cookiecutter.project_slug}}"

    description: "{{ cookiecutter.readme_short_description }}"

    license: "{{ cookiecutter.license }}"

    install: |
      bin.install "{{cookiecutter.project_slug}}"

signs:
  - cmd: cosign
    stdin: "{{ '{{ .Env.COSIGN_PWD }}' }}"
    args:
      ["sign-blob", "--key=cosign.key", "--output-signature=${signature}", "${artifact}"]
    artifacts: all
